apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: sidero-master-1
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: cluster-1
  #node: crash-lab ### If not set it will set automaticly from "pool"
  #vmid: 222  ### If not set it will set automaticly
  pool: prod ### Cluster pool for place VM
  anti-affinity: "" ### The anti-affinity group. VM's with same anti-affinity group will be placed on different nodes
  autostart: true
  autostop: true
  cpu:
    type: host
    sockets: 2
    cores: 1
  memory:
    size: 2048
    balloon: 2048
  network:
    net0:
      model: virtio
      #mac: A2:7B:45:48:9C:E6  ### If not set it will set automaticly
      bridge: vmbr0
      tag: 0 # set to 0 if tag not needed
  disk:
    scsi0:
      storage: local-lvm
      size: 9G
  tags:
    - sidero
    - cluster-0
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=f0ac3f32-ee63-11ed-a05b-0242ac120003,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=net0;ide2;scsi0"
    ide2: "none,media=cdrom"
    hotplug: "network,disk,usb"
    tablet: 1
    onboot: 0
    kvm: 1
    agent: "0"
    numa: 1
    protection: 0
---
apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: sidero-worker-1
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  cluster: cluster-1
  #node: crash-lab ### If not set it will set automaticly from "pool"
  #vmid: 222  ### If not set it will set automaticly
  pool: prod ### Cluster pool for place VM
  anti-affinity: "" ### The anti-affinity group. VM's with same anti-affinity group will be placed on different nodes
  autostart: true
  autostop: true
  cpu:
    type: host
    sockets: 2
    cores: 1
  memory:
    size: 2048
    balloon: 2048
  network:
    net0:
      model: virtio
      #mac: A2:7B:45:48:9C:E6  ### If not set it will set automaticly
      bridge: vmbr0
      tag: 0 # set to 0 if tag not needed
  disk:
    scsi0:
      storage: local-lvm
      size: 9G
  tags:
    - sidero
    - cluster-0
  options:
    ostype: "l26"
    bios: "seabios"
    smbios1: "uuid=fe4fadea-ee63-11ed-a05b-0242ac120003,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
    scsihw: "virtio-scsi-pci"
    boot: "order=net0;ide2;scsi0"
    ide2: "none,media=cdrom"
    hotplug: "network,disk,usb"
    tablet: 1
    onboot: 0
    kvm: 1
    agent: "0"
    numa: 1
    protection: 0